# Header
menu:
  首页: /
  标签: /tags
  归档: /archives
  关于: /about

# Content
excerpt_link: 阅读更多
content_max_width: 800px

# Sidebar
author:
  name: Orange
  work: Web Developer &amp; Designer
  location: Beijing, China
  avatar_url: /images/avatar.jpg

# Links:
links:


# 百度统计
baidu:
  id: e4027971a230b210f4671f485b33846a

# Miscellaneous
rss: /atom.xml
favicon: /images/favicon.ico
